### ISSUE TITLE
err with GDEF version number

### ISSUE THREAD

**Issue by schriftgestalt** [HinTak/Font-Validator#10]
it reports an error:
`GDEF:
E4012	The version number is not 0x00010000	Detail:0x00010002`

The [spec](https://www.microsoft.com/typography/otspec/gdef.htm) says:
> The format 0x00010002 of the GDEF header contains an additional Offset to a list defining mark glyph set definitions (MarkGlyphSetDef):

Related to that, it reports errors about wrong lookup flags that are linked to mark filtering.

**Comment by HinTak** [comment]
This I believe belongs to

https://github.com/Microsoft/Font-Validator/issues/8

Please add a brief note there, file additional report at upstream with details, and possibly also supply a suitable test font file which has the newer version header.

**Comment by HinTak** [comment]
I have added 
https://github.com/HinTak/Font-Validator/commit/d8dec37923b118b05e9733ddc5f51304bf658530
to allow version 0x00010002 and left a number of TODOs for MarkGlyphSetDef all over. Please test (obviously the earlier comment about needing a suitable test font file still applies), and please feel free to tackle the TODOs.

**Comment by HinTak** [comment]
2016-01-22 snapshot and binaries are out, with this change. Do you have a font sample to share? (does not need to be public)

**Comment by schriftgestalt** [comment]
https://github.com/DunwichType/RhodiumLibre/blob/master/RhodiumLibre-Regular.otf

**Comment by HinTak** [comment]
Thanks for the font sample. I'll add checking for the additional field between v1000 and v 1002 at some point.

Apologies for closing the issue items a bit too quickly - in general, I'd like the Microsoft folks to be involved to address some of the issues (if I don't get to them in time) - though they have not been too active. So unless it is about code that I added, I'd prefer issues to be filed upstream. I do get e-mail feeds from upstream.

**Comment by HinTak** [comment]
Hmm, is that the right url/file? I meant one with a v 1002 GDEF table - that one is just a v 1 .

**Comment by schriftgestalt** [comment]
Sorry. I that this file should have it already: Use this: https://dl.dropboxusercontent.com/u/3563666/RhodiumLibre75mk4PS-Regular.otf

**Comment by HinTak** [comment]
Ok, I see two MarkSets now. Check for them will go in the next update.
