### ISSUE TITLE
default location of report (MacOS)

### ISSUE THREAD

**Issue by schriftgestalt** [HinTak/Font-Validator#11]
Why is the `-report-in-font-dir` not the default?

**Comment by HinTak** [comment]
Please file upstream and let the Microsoft folks answer this question.

Here is my understanding of how the code works: there are 3 locations in the GUI, temp for immediate display (and delete on close), font dir, and user-specified central location (for multiple fonts per test). These are inherited by the later command line tool.

The first one does not make sense for command line usage as there is no viewer - though one might be tempted to dump to console; the 2nd one has the disadvantage of not usable for read-only media or privilege issues (writing to system location etc), the 3rd one suffers from collision if two fonts from two locations shares the same name.

I personally use the 3rd option most often, and don't like the 2nd (it pollutes my font collections...) but I suppose the 2nd option is favoured by people who also created the font being tested. I think the command line inherits the default choice from the GUI and defaults to the first, which is a bit stupid, but I don't necessarily think the 2nd is the answer; I'll think about disable/abort on neither 2nd nor 3rd.

**Comment by HinTak** [comment]
Btw, 2016-01-22 switched the default to the user's desktop.
