### ISSUE TITLE
build issue on Ubuntu Xenial

### ISSUE THREAD

**Issue by n7s** [HinTak/Font-Validator#24]
on Ubuntu xenial (with mono-mcs 4.2.1.102+dfsg2-7ubuntu4) I'm getting these build errors: 

make[1]: Leaving directory '/home/nico/repos/fontval-ht'
make[1]: Entering directory '/home/nico/repos/fontval-ht'
( cd OTFontFileVal && \
        mcs -debug- -optimize+ -lib:../bin/  \
            -r:Compat -r:System.Windows.Forms \
            -r:OTFontFile -r:ValCommon -r:Glyph -r:GMath \
    -resource:OTFontFileVal.ValStrings.resources \
            -target:library -out:../bin/OTFontFileVal.dll *.cs )
ValDriver.cs(92,41): warning CS0168: The variable `e' is declared but never used
ValDriver.cs(310,20): warning CS0219: The variable `sTable' is assigned but its value is never used
val_CFF.cs(115,25): warning CS0219: The variable `name' is assigned but its value is never used
val_CFF.cs(128,25): warning CS0219: The variable `a' is assigned but its value is never used
val_VDMX.cs(139,32): warning CS0219: The variable `ratio' is assigned but its value is never used
val_cmap.cs(645,32): warning CS0219: The variable `charbuf' is assigned but its value is never used
val_hhea.cs(394,28): warning CS0219: The variable `dItalicAngle' is assigned but its value is never used
val_post.cs(74,49): error CS0117: `OTFontFileVal.W' does not contain a definition for `post_W_Version_3_Apple'
atoms.cs(5,17): (Location of the symbol related to previous error)
val_post.cs(78,49): error CS0117: `OTFontFileVal.W' does not contain a definition for `post_W_Version_4_Apple'
atoms.cs(5,17): (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 7 warnings
Makefile:145: recipe for target 'bin/OTFontFileVal.dll' failed
make[1]: *** [bin/OTFontFileVal.dll] Error 1
make[1]: Leaving directory '/home/nico/repos/fontval-ht'
Makefile:73: recipe for target 'default' failed
make: *** [default] Error 2

Thanks for any insights. 

Let me know how I can help with this.

**Comment by HinTak** [comment]
My fault - two of the files (plus the documentation chm) need to be re-generated whenever new tests are added. You do:

```
$ make gendoc
$ pushd  GenerateFValData/bin/Debug/
$ mono GenerateFValData.exe 
$ popd
$ resgen OTFontFileVal/OTFontFileVal.ValStrings.resx
```

I meant to add this to the buiild instruction for a long time, but waiting for 

https://bugzilla.xamarin.com/show_bug.cgi?id=34091
"resgen introduces dependency to versioned System.Windows.Forms"

to be fixed to add it. So now this is documented here... This should go into the README.

Currrently building the chm requires manually patching the central index plus running Microsoft htmlhelp worksop (under wine). This should be documented as well. But the newly filled "NewHelp" directory contain html help which is largely functional as is.

And if you are a purist you might want to build SharpFont from source (my fork) also .

**Comment by HinTak** [comment]
Oh, and my fork of mono-webbrowser (only the GUI needs it, as well as webkit-sharp). My private fork of freetype - not yet public - contains the rasterization/hinting test. The C# code auto-detects whether the freetype present is suitable and does the right thing (i.e. go ahead and run that part of test or tell the user detected freetype isn't enhanced).

So this post explains why all the binary blobs are in bin .
