### ISSUE TITLE
xAvgCharWidth is calculated differently by fontTools and FontVal

### ISSUE THREAD

**Issue by madig** [HinTak/Font-Validator#33]
See https://github.com/googlei18n/ufo2ft/issues/195. Not sure what to make of it.

**Comment by HinTak** [comment]
https://github.com/HinTak/Font-Validator/blob/master/OTFontFileVal/val_OS2.cs - line 105, does one way of calculation when OS/2 table is "exactly 3", and does something else if not. It should be changed to "larger than or equal to 3".

**Comment by HinTak** [comment]
Thanks for the report. I'll make the change and close this now. Please pull and rebuild.
