### ISSUE TITLE
Warning W1113 does not divulge which glyph has degenerated contours

### ISSUE THREAD

**Issue by madig** [HinTak/Font-Validator#39]
One of our fonts triggers this: `W1113 Degenerated contour(s), Number of glyphs with the warning = 1`. I guess the code to find these contours is at https://github.com/HinTak/Font-Validator/blob/master/Glyph/GErr.cs#L980, however:

1. I don't understand what the code does
2. It doesn't seem to use indGlyphOwner to note down the specific glyph index

I'd prepare a patch to fix 2., but the specifics string doesn't even seem to be used in the report?!

**Comment by HinTak** [comment]
Sorry, the documentation is here:

https://github.com/HinTak/Font-Validator/blob/master/NewHelp/W1113.htm

Eventually it should be merged into here:
https://github.com/HinTak/Font-Validator/blob/master/GenerateFValData/OurData.xml

There are a few issues related to this, 
https://github.com/Microsoft/Font-Validator/issues/60
https://github.com/Microsoft/Font-Validator/issues/17

This issue probably should be re-opened:
https://github.com/Microsoft/Font-Validator/issues/15

I am surprised that it does not mention a glyph index. Can you send me a test file (if necessary, privately) to have a look?

**Comment by madig** [comment]
(Sent to your at-users.sourceforge.net address)

**Comment by HinTak** [comment]
Argh, I saw this problem while testing visual-studio-2008-built FontVal 2.1.3 with Microsoft's times - I 'll look into it at some point.

**Comment by HinTak** [comment]
@madig : I tagged 2.1.4 a few days ago and just made the windows build and you can use that now. Wait a few days if you want/need the mac/linux builds.

**Comment by HinTak** [comment]
@madig : the 2.1.4 mac/linux binaries with this fix are up . Would be interested in what you find - whether they are single point contours in the u200x unicode space range or something else.
