### ISSUE TITLE
cmap: non-BMP encoding ID for platform 0 is 4, not 10

### ISSUE THREAD

**Issue by madig** [HinTak/Font-Validator#49]
When a font has non-BMP characters and a `cmap` table for platform ID 0 (Unicode), the encoding ID must be 4. FontVal complains that it must be 10, which is correct only for the platform ID 3 (Windows).

**Comment by Pomax** [comment]
Can you point to where in the spec this is defined?

**Comment by twardoch** [comment]
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html

**Comment by twardoch** [comment]
(Platform 0 is defined in the TrueType spec, the OpenType spec defines no
semantics for it. But as with all tables common to TrueType and OpenType,
both specs should be considered together unless they contradict each other.)

**Comment by HinTak** [comment]
Fixed in https://github.com/HinTak/Font-Validator/commit/9e7337fb33a17d41ac90881ee47a1e102e9c50a3 - I hope - since you didn't supply a test file. Thanks for the report.
