### ISSUE TITLE
"Input string was not in a correct format" on Arabic Transparent font

### ISSUE THREAD

**Issue by snoopy-coder** [HinTak/Font-Validator#52]
I'm just trying to execute the command:
**FontValidator.exe -file artro.ttf**
and I get the following error:
**Input string was not in a correct format**

_FontVal 2.1.4_
OS: _Windows 7 x64_
Font: _Arabic Transparent (TrueType),_ it can be downloaded [here](https://www.upload.ee/files/10585294/artro.rar.html)

**Comment by HinTak** [comment]
Can't reproduce the issue - here are the reports generated from those two font files, with two minus changes - editing out my computer's name, and appended .txt to the file names to let github attach.

BTW, please don't use upload.ee (too much porn-related pop-ups), and I suspect you do not work for monotype, and do not own the copyright of those font files either - i.e. you don't have distribution rights to post them publicly...

[artrbdo.ttf.report.html.txt](https://github.com/HinTak/Font-Validator/files/3814231/artrbdo.ttf.report.html.txt)
[artro.ttf.report.xml.txt](https://github.com/HinTak/Font-Validator/files/3814232/artro.ttf.report.xml.txt)
[artrbdo.ttf.report.xml.txt](https://github.com/HinTak/Font-Validator/files/3814233/artrbdo.ttf.report.xml.txt)
[artro.ttf.report.html.txt](https://github.com/HinTak/Font-Validator/files/3814234/artro.ttf.report.html.txt)

I have not seen that messge in any context before...

**Comment by snoopy-coder** [comment]
> Can't reproduce the issue

I have for some time thought about your words and came to the conclusion that such behavior is related to the settings of `Region and Language`. I have not previously mentioned that I had originally set `Russian` format (date, time, numbers, separators, etc.) If I change the format to `English (US)`, the error disappears and I get a result similar to yours.
[http://ipic.su/7yHdSp.jpg](http://ipic.su/7yHdSp.jpg)
[http://ipic.su/7yHdSt.jpg](http://ipic.su/7yHdSt.jpg)

> I suspect you do not work for monotype, and do not own the copyright of those font files either 

Very perceptive! :smile: I just copied/pasted a link to that file sharing resource, not caring about the consequences. These fonts are not really mine, but they clearly have some flaw. And with the help `FontVal` I was hoping to find out what it is.
In principle, the issue can be closed, because the cause is found. But I want you to know about the working solution.

**Comment by HinTak** [comment]
I'll leave the issue open - thanks for letting me know. I'll see what needs to be done on unusual locale.

**Comment by Antiever** [comment]
Looks like all 2.x.x versions crash with a lot of edited files.
However v1.0.1 did the job and instead of crash just log this error in report
https://i.imgur.com/6yFkArn.png

**Comment by HinTak** [comment]
That's interesting. I don't have access to the 1.0.1 source code, but I know they did some reorganization before they opened it. It looks like a try {} catch {} was lost during the reorganization. I 'll see where that might be and put it back. Don't know when I'd find time to do it though.

**Comment by schriftgestalt** [comment]
(Just a side note: why are you storing images on external servers? Just drag the image into to edit field on GitHub and they show up directly)

**Comment by HinTak** [comment]
Fixes non-English locale formatting issue in https://github.com/HinTak/Font-Validator/commit/46cd98a6b18d7f4e3aa7b9aac3e316285c34577a
