### ISSUE TITLE
false E2113 for high Unicode

### ISSUE THREAD

**Issue by StevanWhite** [HinTak/Font-Validator#54]
E2113
A unicode range was indicated in ulUnicodeRange, but the font has no characters in that range
No 'Gothic' characters are present

Yet the font does have a full set of characters in the Gothic range.

This is observed when ulUnicodeRange is set for certian other ranges as well.

Perhaps the problem might be triggered by the Gothic range being beyond U+10000.
Or perhaps a list of ranges is out of date.

**Comment by HinTak** [comment]
Thanks for letting me know. Do you have such a font to share? Privately is fine - htl10 at users.sourceforge.net should do.

**Comment by StevanWhite** [comment]
Hi,

Sure.  GNU FreeFont.  Send me your e-mail and I'll send you a link to a
build.

Or you can build it yourself from SVN.
https://savannah.gnu.org/svn/?group=freefont

I had a look at the FontValidator code.
As you know, it is programmed in a very primitive, C-like style.
The code around this problem (OTFont.cs) would be vastly simpler and faster
and more economical of memory with a couple of Generic Dictionaries, and
that would make this problem easy to fix, too.

But the code looks extremely fragile.  I'm not enthusiastic about touching
it.

**Comment by HinTak** [comment]
That's fine - a svn revision branch + number would be good too, just in case it is transient etc.

**Comment by StevanWhite** [comment]
Rev. 4143 is what I have.  But it has been giving this error for
years.  I just now got around to reporting it.

I notice the errors in the OS/2 section vary a lot on the OS/2
version, and with the version of FontForge I use.  With the distro
FontForge on Linux Mint, and the OS/2 version set to 4, a whole class
of errors in the OS/2 section go away.  But this one I reported is
still there.

No copy of FontForge that I have shows version 5 in the OS/2 version
list.  If I type a 5 in, FontValidator says the OS/2 table is
"corrupted".

Could it be that this problem occurs because of the OS/2 version?

But no... that OTFont.cs file has lots of places where it craps out
for higher Unicode...
Pretty sure it can't all be right.

**Comment by HinTak** [comment]
That's most likely it . When FontVal was open-sourced , it accepts os/2 version 3 only, as far as I remember. I think I added v4, and possibly incomplete v5. There is probably a few "TODO" around that for reminding myself it needs more work.
You are right using dictionaries would simplify the code. I also remember that it was difficult to support dotnet 2 (the original run time it was based on - around 2003?) because the dictionary generic in that release had a few limitations, like missing some convenient constructors found in later releases. We (I mean 'I') still support dotnet 2, for side-by-side comparison with the older proprietary backend.
Anyway, I 'll look into this soon.

**Comment by StevanWhite** [comment]
Hi,

Now you've got me looking at the code.  I saw a magic number FFFF in
OTFile.cs, and where it was passing a glyph ID as a C short in building a
cache.  I made that better... but the issue persists.  But now that I look,
there are lots of cases of this sort of thing.

Also, I recall some years ago trying to increase the OS/2 version number to
4 in the font... but for some reason I put it back.  It may have been that
the old MS FontValidator complained about something.  I can't think of any
reason not to set it to 4.

**Comment by HinTak** [comment]
@StevanWhite : can you attach your build to this issue please? I think zipping up all the otf/ttf should be within the 10MB or 30MB limit of github's issue attachment - or I just need one font file, really.

I git-svn cloned the repo (a bit crazy that it requires about 3.9GB temp, to compress down to about 140MB history plus 35MB check out), then it says it requires a special fontforge that's 8 years old. What's shipped with fedora (august 2019) is too new... Have you consider telling Frank at fontforge about it? Anyway, I am very much not going to build 8-year-old fontforge to build this... I have got a build of GNU freefont alright (maybe incorrectly), but I might as well get your build, if it needs antique fontforge to build correctly

On the cmap note, you can do 'ftdump -c ...' to see what charmap it ships and what coverage it has under that particular charmap. It seems that the -c/-C option is new (I think the info under -C used to put under -v, with -V being the version) so you might need a new-ish ftdump, or look at the help page of your version of ftdump . (from freetype-demos - I assume you have at least heard of it!)

**Comment by HinTak** [comment]
Fixed in https://github.com/HinTak/Font-Validator/commit/2818af58d6d774bef6f86a93736b3c28ef6866bd . Thanks for the report. Yes, it is an oversight of the Microsoft folks - but back in 2003 (or up to 2009 when this code was abandoned) non-BMP fonts were rare.

**Comment by StevanWhite** [comment]
Muchas gracias!
