### ISSUE TITLE
Spurious E5700 when Mark Sets are used

### ISSUE THREAD

**Issue by StevanWhite** [HinTak/Font-Validator#56]
Every lookup using Mark Sets produces an error E5700:
The LookupFlag reserved bits are not all set to zero

It would be very helpful to check the consistency of Mark Sets however.  At least:

LookupFlag bit field
-         useMarkFilteringSet (0x0010)
If set, it must check that
-         the LookupHeader includes a MarkFilteringSet
-         a MarkGlyphSetsTable is present in the GDEF table
Further, the Mark Glyph Sets consistency should be checked:
-         markGlyphSetTableFormat must be 1
-         markGlyphSetCount should be bigger than 0
Each coverage table in coverageOffsets should be checked for consistency:
-         Each glyph in the table must be present in the font.

**Comment by HinTak** [comment]
Fixed in https://github.com/HinTak/Font-Validator/commit/9021bad28bc2f86ef53b2ed064c95c8edb6b6b2b . MarkFilterSet was added in 2009/2010, after the Microsoft folks stopped working on FontVal. Thanks for the report.
