### ISSUE TITLE
The modified time is an unlikely value

### ISSUE THREAD

**Issue by devosb** [HinTak/Font-Validator#66]
The title of this issue comes from W1311. I think there is a bug in this warning. The font gets a timestamp when built, and the timezone used seems to be UTC. So for a font I just built, at 08:46 in North America (UTC-7) FontValidator reports a time of 15:46. But if timezones are ignored, 15:46 is in the future compared to 08:46, and I suspect being in the future counts as _unlikely_. If I wait just over 7 hours before re-running (and not rebuilding the font) then FontValidator does not give this error when checking the (by then) 7+ hour old font.

**Comment by HinTak** [comment]
The spec indeed says values are in UTC : https://docs.microsoft.com/en-us/typography/opentype/spec/head - I 'll see what the code says.

**Comment by HinTak** [comment]
Should be fixed in https://github.com/HinTak/Font-Validator/commit/a34447e499a3f6dde375eceb8d75b69c647fd854 . I think the main problem is that 1904 Jan 1 was taken as local.
