### ISSUE TITLE
typo in GDEF version check message (P4006)

### ISSUE THREAD

**Issue by seehuhn** [HinTak/Font-Validator#70]
Font-Validator 2.1.6 shows the following explanation for the GDEF version check (P4006): "The version numbers 0x00010000 or 0x0001002 are okay".  I believe a "0" is missing for the second option: it should be 0x00010002 (8 digits) instead of 0x0001002 (7 digits).

**Comment by HinTak** [comment]
Thanks for spotting this. Fixed in https://github.com/HinTak/Font-Validator/commit/435ec1e2b49bba82231442bdebf63bcad28c70b1 - luckily it is just cosmetic - the check code is correct.
